### ISSUE TITLE
rbenv won't install ruby 2.3.0

### ISSUE THREAD

**Issue by matthewsalan** [brossetti1/abnb-manager#1]
You have any issues with rbenv and installing ruby ```2.3.0?```  I updated brew and upgraded ruby-build, but rbenv doesn't list ```2.3.0``` as an option, only ```2.3.0-dev```.

**Comment by brossetti1** [comment]
have you tried  `brew update && brew upgrade ruby-build`

then run `rbenv install 2.3.0` ?

**Comment by brossetti1** [comment]
have you tried

 `brew update && brew upgrade ruby-build`

then run `rbenv install 2.3.0`

with warm regards,

Brian Rossetti

tel:415.527.6345

@skype - brian.rossetti17

On Wed, Mar 02, 2016 at 5:34 PM Alan Matthews

<
mailto:Alan Matthews <notifications@github.com>
> wrote:

You have any issues with rbenv and installing ruby

2.3.0?

I updated brew and upgraded ruby-build, but rbenv doesn't list

2.3.0

as an option, only

2.3.0-dev

.

—

Reply to this email directly or
https://github.com/brossetti1/abnb-manager/issues/1
.

https://github.com/brossetti1/abnb-manager/issues/1

**Comment by matthewsalan** [comment]
Yeah, I have the current version of ```ruby-build``` and ```brew```.  Not sure what's up.  Opening an issue with the maintainers of ```rbenv/ruby-build```.

**Comment by matthewsalan** [comment]
Bloody hell, got this fixed finally!!

**Comment by brossetti1** [comment]
haha, hey Alan, sorry i didn’t respond after the first time, I’m out in Bali now, I will be back in May, ill hit you up, we can get together and mess around with this

with warm regards,

Brian Rossetti

tel:415.527.6345

@skype - brian.rossetti17

On Mon, Mar 14, 2016 at 8:43 PM Alan Matthews

<
mailto:Alan Matthews <notifications@github.com>
> wrote:

Closed
https://github.com/brossetti1/abnb-manager/issues/1
.

—

You are receiving this because you commented.

Reply to this email directly or view it on GitHub:
https://github.com/brossetti1/abnb-manager/issues/1#event-589585414
https://github.com/brossetti1/abnb-manager/issues/1#event-589585414

**Comment by matthewsalan** [comment]
Yeah, fuck you and your Southeast Asia trip!!  Dylan told me about it yesterday.  No worries, just started a new gig at CallRail so I'm heads down with that for now.  Have fun!
